#! /bin/bash

cmd=$1

case $1 in
  "up") docker run -ti -d --name $2 --rm -v `pwd`:/app scala bash;;
  "new") docker exec -ti $2 sbt new sbt/scala-seed.g8;;
  "repl") docker exec -ti $2 bash -c "cd ./$3 && sbt";;
esac
